import AppKit

/// Polls the system pasteboard for changes and converts new contents
/// into `ClipboardItem`s. Skips transient/concealed data so password
/// managers and auto-generated pasteboard contents are never captured.
final class ClipboardMonitor {
    var onItem: (@MainActor (ClipboardItem) -> Void)?

    private var timer: Timer?
    private var lastChangeCount: Int
    private let imagesDirectory: URL

    /// Pasteboard type identifiers that mark content we must never store.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "de.petermaurer.AutogeneratedPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.isaacwogan.Transitory",
    ]

    init(imagesDirectory: URL) {
        self.imagesDirectory = imagesDirectory
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    deinit {
        timer?.invalidate()
    }

    /// Call after writing to the pasteboard ourselves so the write isn't
    /// reported back as new user content.
    func swallowPendingChange() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        let sourceName = sourceApp?.localizedName
        // Never record copies that came from ClipStack itself.
        if sourceApp?.bundleIdentifier == Bundle.main.bundleIdentifier { return }

        let item = makeItem(from: pasteboard, sourceApp: sourceName)
        guard let item else { return }
        let callback = onItem
        Task { @MainActor in callback?(item) }
    }

    private func makeItem(from pasteboard: NSPasteboard, sourceApp: String?) -> ClipboardItem? {
        // File URLs (Finder copies) — checked first since they also carry a string.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            return ClipboardItem(
                kind: .file,
                text: paths.joined(separator: "\n"),
                filePaths: paths,
                sourceAppName: sourceApp,
                contentHash: ClipboardItem.hash(paths.joined(separator: "|"))
            )
        }

        // Images — prefer PNG payload, fall back to TIFF (converted to PNG).
        let imageData = pasteboard.data(forType: .png)
            ?? pasteboard.data(forType: .tiff).flatMap { tiff -> Data? in
                guard let rep = NSBitmapImageRep(data: tiff) else { return nil }
                return rep.representation(using: .png, properties: [:])
            }
        if let imageData {
            guard let fileName = saveImage(imageData) else { return nil }
            return ClipboardItem(
                kind: .image,
                imageFileName: fileName,
                sourceAppName: sourceApp,
                contentHash: ClipboardItem.hash(data: imageData)
            )
        }

        // Text / links.
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let isLink = trimmed.range(of: #"^https?://\S+$"#, options: .regularExpression) != nil
            return ClipboardItem(
                kind: isLink ? .link : .text,
                text: string,
                sourceAppName: sourceApp,
                contentHash: ClipboardItem.hash(string)
            )
        }

        return nil
    }

    private func saveImage(_ data: Data) -> String? {
        let fileName = UUID().uuidString + ".png"
        do {
            try data.write(to: imagesDirectory.appendingPathComponent(fileName), options: .atomic)
            return fileName
        } catch {
            return nil
        }
    }
}
